// angular/src/app/components/main-dropdown/main-dropdown.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'main-dropdown',
  templateUrl: './main-dropdown.component.html',
  styleUrls: ['./main-dropdown.component.scss']
})
export class MainDropdownComponent implements OnInit {
  @Input() countries: Array<Object>;
  @Output() onChange: EventEmitter<any> = new EventEmitter();

  constructor() { }

  ngOnInit() { }

  changeValue(value) {
    this.onChange.emit(value);
  }
}

<select class="MainDropdown" (change)="changeValue($event.target.value)">
  <option value="default">Select a country</option>
  <option *ngFor="let country of countries" [value]="country.Slug + ',' + country.ISO2">{{ country.Country }}</option>
</select>

// vue/src/components/MainDropdown.vue
<template>
  <div id="MainDropdown">
    <select class="MainDropdown" @change="changeValue">
      <option value="default">Select a country</option>
      <option
        v-for="item in data"
        :key="item.ISO2"
        :value="`${item.Slug},${item.ISO2}`"
        >{{ item.Country }}</option
      >
    </select>
  </div>
</template>

<script>
export default {
  name: "MainDropdown",
  props: ["data"],
  methods: {
    changeValue: function(event) {
      this.$emit("changeValue", event.target.value);
    }
  }
};
</script>

<style lang="scss">
@import "@/assets/css/components/MainDropdown.scss";
</style>
