// react-functional/src/components/MainDropdown.js
import React from 'react';

// css
import '../assets/css/components/MainDropdown.scss';

function MainDropdown(props) {
  return props.data && (
    <select className="MainDropdown" onChange={ (event) => props.onChange(event.target.value) }>
      {
        props.data.data.map(country => {
          return <option key={ country.ISO2 } value={ country.Slug }>{ country.Country }</option>;
        })
      }
    </select>
  )
}

export default MainDropdown;

// vue/src/components/MainDropdown.vue
<template>
  <div id="MainDropdown">
    <select class="MainDropdown" @change="changeValue">
      <option value="default">Select a country</option>
      <option
        v-for="item in data"
        :key="item.ISO2"
        :value="`${item.Slug},${item.ISO2}`"
        >{{ item.Country }}</option
      >
    </select>
  </div>
</template>

<script>
export default {
  name: "MainDropdown",
  props: ["data"],
  methods: {
    changeValue: function(event) {
      this.$emit("changeValue", event.target.value);
    }
  }
};
</script>

<style lang="scss">
@import "@/assets/css/components/MainDropdown.scss";
</style>
