// react-class/src/containers/DeadGraphContainer.js
import React, { Component } from 'react';

// contexts
import CovidContext from '../contexts/CovidContext';

// components
import Title02 from '../components/Title02';
import Title03 from '../components/Title03';
import MainDropdown from '../components/MainDropdown';
import MainChart from '../components/MainChart';
import MainButton from '../components/MainButton';

// rest
import { getByCountry } from '../rest/data/CovidData';

// helpers
import { getPopulationByCountry, countViews } from '../helpers/Helper';

export default class DeadGraphContainer extends Component {
  static contextType = CovidContext;

  constructor(props) {
    super(props);
    this.state = {
      countryCode: null,
      prevCountryCode: null,
      chartData: null,
      showChart: false,
      data: [],
      axes: [
        { primary: true, type: 'utc', position: 'bottom' },
        { type: 'linear', position: 'left' }
      ],
      population: 0,
      count: 0
    };

    // bindings
    this.changeValueDropdown = this.changeValueDropdown.bind(this);
  }

  async componentDidUpdate(prev, current) {
    if ((current.countryCode !== current.prevCountryCode) && current.countryCode) {
      this.setState({ 
        population: await getPopulationByCountry(this.state.countryCode),
        prevCountryCode: current.countryCode
      });
    }
  }

  async changeValueDropdown(country) {
    if (country !== 'default') {
      this.setState({ count: countViews(this.state.count, 'increment') });
      let countryValues = country.split(',');
      this.setState({ countryCode: countryValues[1] });
      let deadStats = await getByCountry(countryValues[0], 'deaths');
      let tempChartData = [];
      deadStats.data.map(deadStat => {
        return tempChartData.push({ x: new Date(deadStat.Date), y: deadStat.Cases });
      });
      this.setState({
        data: [
          {
            label: 'Dead covid-19 patients',
            data: tempChartData
          }
        ],
        showChart: deadStats.data.length !== 0
      });
    }
    else this.setState({ showChart: false });
  }

  render() {
    return (
      <>
        <Title02 title="Graph dead patients" /> 
        <MainDropdown data={ this.context.countries } onChange={ this.changeValueDropdown } />
      { this.state.showChart && (
        <>
            <MainChart axes={ this.state.axes } data={ this.state.data } />
            <Title03 title="Some details..." />
            <p>In this country live { this.state.population } people</p>
            <p>You checked { this.state.count } countries</p>
            <MainButton text="Delete previous count" action={ () => this.setState({ count: countViews(this.state.count, 'decrement') }) } />
          </>
        ) 
      }
      </>
    );
  }
}

// angular/src/app/containers/dead-graph-container/dead-graph-container.component.ts
import { Component, OnInit } from '@angular/core';
import { Chart } from 'chart.js';

// services
import { GlobalsService } from '../../services/globals-service/globals.service';
import { CovidService } from '../../services/covid-service/covid.service';
import { PopulationService } from '../../services/population-service/population.service';

// classes
import { Population } from '../../classes/population/population';
import { Count } from '../../classes/count/count';

@Component({
  selector: 'app-dead-graph-container',
  templateUrl: './dead-graph-container.component.html',
  styleUrls: ['./dead-graph-container.component.scss']
})
export class DeadGraphContainer implements OnInit {
  public countries: Array<Object>;
  public showChart: Boolean = false;
  private countryCode: string = 'BE';
  public chart: any = [];
  private cases: Array<Number> = [];
  private dates: Array<any> = [];
  public population: number;
  public count: number = 0;
  private countInstance: Count;

  constructor(
    private globalsService: GlobalsService,
    private covidService: CovidService,
    private populationService: PopulationService
  ) { 
    this.countInstance = new Count();
  }

  ngOnInit() { }

  // In ngOnInit, the value wasn't set before asking the value
  ngDoCheck() {
    this.countries = this.globalsService.getCountries();
  }

  async changeValueDropdown(country) { 
    if (country !== "default") {
      this.count = this.countInstance.increaseCount();
      let countryValues = country.split(",");
      this.countryCode = countryValues[1];
      await (await this.covidService.getByCountry(countryValues[0], "deaths")).subscribe(res => {
        this.createChart(res);
      });
      let populationInstance = new Population(this.populationService);
      this.population = await populationInstance.getPopulation(this.countryCode);
    } else this.showChart = false;
  }

  removeCount() {
    this.count = this.countInstance.decreaseCount();
  }

  createChart(data) {
    if (this.chart.length !== 0) this.chart.destroy();
    this.cases = [];
    this.dates = [];
    data.map(item => {
      this.cases.push(item.Cases);
      this.dates.push(item.Date.split('T')[0]);
    });
    if (data.length !== 0) {
      this.chart = new Chart('canvas', {
        type: 'line',
        data: {
          labels: this.dates,
          datasets: [
            {
              data: this.cases,
              borderColor: '#9E2C29',
              fill: false
            }
          ]
        },
        options: {
          legend: {
            display: false
          },
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              display: true
            }],
          }
        }
      });
    }
    else {
      this.chart = [];
    }
  }
}

<title02 title="Graph dead patients"></title02>
<main-dropdown [countries]="countries" (onChange)="changeValueDropdown($event)"></main-dropdown>
<br />
<canvas id="canvas">{{ chart }}</canvas>
<div *ngIf="chart.length !== 0">
  <title03 title="Some details..."></title03>
  <p>In this country live {{ population }} people</p>
  <p>You checked {{ count }} countries</p>
  <main-button text="Delete previous count" (onClick)="removeCount()"></main-button>
</div>
