// react-functional/src/containers/ConfirmedGraphContainer.js
import React, { useContext, useCallback, useMemo, useState, useReducer } from 'react';

// components
import Title02 from '../components/Title02';
import Title03 from '../components/Title03';
import MainDropdown from '../components/MainDropdown';
import MainChart from '../components/MainChart';
import MainButton from '../components/MainButton';

// contexts
import { CovidContext } from '../contexts/CovidProvider';

// rest
import { getByCountry } from '../rest/data/CovidData';

// hooks - reducers
import { countReducer } from '../hooks/Reducers';

// hooks - custom
import useGetpopulation from '../hooks/customs/useGetPopulation';

function ConfirmedGraphContainer() {
  const covidContext = useContext(CovidContext);
  const [showChart, setShowChart] = useState(false);
  const [chartData, setChartData] = useState(null);
  const [countryCode, setCountryCode] = useState(null);
  const [state, dispatch] = useReducer(countReducer, { count: 0 });
  const population = useGetpopulation(countryCode);

  const changeValueDropdown = useCallback(async country => {
    if (country !== 'default') {
      dispatch({ type: 'increment' });
      let countryValues = country.split(',');
      setCountryCode(countryValues[1]);
      let confirmedStats = await getByCountry(countryValues[0], 'confirmed');
      let tempChartData = [];
      confirmedStats.data.map(confirmedStat => {
        return tempChartData.push({ x: new Date(confirmedStat.Date), y: confirmedStat.Cases });
      });
      setChartData(tempChartData);
      setShowChart(confirmedStats.data.length !== 0);
    }
    else setShowChart(false);
  }, []);

  /* Data used by chart */
  const data = useMemo(() => [
    {
      label: 'Confirmed covid-19 patients',
      data: chartData
    }
  ], [chartData]);

  const axes = useMemo(() => [
    { primary: true, type: 'utc', position: 'bottom' },
    { type: 'linear', position: 'left' }
  ], []);

  return (
    <>
      <Title02 title="Graph confirmed patients" /> 
      <MainDropdown data={ covidContext.countries } onChange={ changeValueDropdown } />
      { (showChart && chartData) && (
        <>
            <MainChart axes={ axes } data={ data } />
            <Title03 title="Some details..." />
            <p>In this country live { population } people</p>
            <p>You checked { state === undefined ? '...' : state.count } countries</p>
            <MainButton text="Delete previous count" action={ () => dispatch({ type: 'decrement' }) } />
          </>
        ) 
      }
    </>
  );
}

export default ConfirmedGraphContainer;

// angular/src/app/containers/confirmed-graph-container/confirmed-graph-container.component.ts
import { Component, OnInit } from '@angular/core';
import { Chart } from 'chart.js';

// services
import { GlobalsService } from '../../services/globals-service/globals.service';
import { CovidService } from '../../services/covid-service/covid.service';
import { PopulationService } from '../../services/population-service/population.service';

// classes
import { Population } from '../../classes/population/population';
import { Count } from '../../classes/count/count';

@Component({
  selector: 'app-confirmed-graph-container',
  templateUrl: './confirmed-graph-container.component.html',
  styleUrls: ['./confirmed-graph-container.component.scss']
})
export class ConfirmedGraphContainer implements OnInit {
  public countries: Array<Object>;
  public showChart: Boolean = false;
  private countryCode: string = 'BE';
  public chart: any = [];
  private cases: Array<Number> = [];
  private dates: Array<any> = [];
  public population: number;
  public count: number = 0;
  private countInstance: Count;

  constructor(
    private globalsService: GlobalsService,
    private covidService: CovidService,
    private populationService: PopulationService
  ) { 
    this.countInstance = new Count();
  }

  ngOnInit() { }

  // In ngOnInit, the value wasn't set before asking the value
  ngDoCheck() {
    this.countries = this.globalsService.getCountries();
  }

  async changeValueDropdown(country) { 
    if (country !== "default") {
      this.count = this.countInstance.increaseCount();
      let countryValues = country.split(",");
      this.countryCode = countryValues[1];
      await (await this.covidService.getByCountry(countryValues[0], "confirmed")).subscribe(res => {
        this.createChart(res);
      });
      let populationInstance = new Population(this.populationService);
      this.population = await populationInstance.getPopulation(this.countryCode);
    } else this.showChart = false;
  }

  removeCount() {
    this.count = this.countInstance.decreaseCount();
  }

  createChart(data) {
    if (this.chart.length !== 0) this.chart.destroy();
    this.cases = [];
    this.dates = [];
    data.map(item => {
      this.cases.push(item.Cases);
      this.dates.push(item.Date.split('T')[0]);
    });
    if (data.length !== 0) {
      this.chart = new Chart('canvas', {
        type: 'line',
        data: {
          labels: this.dates,
          datasets: [
            {
              data: this.cases,
              borderColor: '#9E2C29',
              fill: false
            }
          ]
        },
        options: {
          legend: {
            display: false
          },
          scales: {
            xAxes: [{
              display: true
            }],
            yAxes: [{
              display: true
            }],
          }
        }
      });
    }
    else {
      this.chart = [];
    }
  }
}
<title02 title="Graph confirmed patients"></title02>
<main-dropdown [countries]="countries" (onChange)="changeValueDropdown($event)"></main-dropdown>
<br />
<canvas id="canvas">{{ chart }}</canvas>
<div *ngIf="chart.length !== 0">
  <title03 title="Some details..."></title03>
  <p>In this country live {{ population }} people</p>
  <p>You checked {{ count }} countries</p>
  <main-button text="Delete previous count" (onClick)="removeCount()"></main-button>
</div>
