// vue/src/components/Header.vue
<template>
  <header>
    <h1>
      <router-link to="confirmed">COVID-19</router-link>
    </h1>
    <nav>
      <ul>
        <li>
          <router-link to="/confirmed">Confirmed</router-link>
        </li>
        <li>
          <router-link to="/cured">Cured</router-link>
        </li>
        <li>
          <router-link to="/dead">Dead</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: "Header"
};
</script>

<style lang="scss">
@import "@/assets/css/components/Header.scss";
</style>

// react-functional/src/components/Header.js
import React from 'react';
import { Link } from '@reach/router';

// css
import '../assets/css/components/Header.scss';

function Header() {
  return (
    <header>
      <h1>
        <Link to="confirmed">COVID-19</Link>
      </h1>
      <nav>
        <ul>
          <li>
            <Link to="/confirmed">Confirmed</Link>
          </li>
          <li>
            <Link to="/cured">Cured</Link>
          </li>
          <li>
            <Link to="/dead">Dead</Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;
