// vue/src/components/MainDropdown.vue
<template>
  <div id="MainDropdown">
    <select class="MainDropdown" @change="changeValue">
      <option value="default">Select a country</option>
      <option
        v-for="item in data"
        :key="item.ISO2"
        :value="`${item.Slug},${item.ISO2}`"
        >{{ item.Country }}</option
      >
    </select>
  </div>
</template>

<script>
export default {
  name: "MainDropdown",
  props: ["data"],
  methods: {
    changeValue: function(event) {
      this.$emit("changeValue", event.target.value);
    }
  }
};
</script>

<style lang="scss">
@import "@/assets/css/components/MainDropdown.scss";
</style>

// react-class/src/components/MainDropdown.js
import React, { Component } from 'react';

// css
import '../assets/css/components/MainDropdown.scss';

export default class MainDropdown extends Component {
  render() {
    return this.props.data && (
      <select className="MainDropdown" onChange={ (event) => this.props.onChange(event.target.value) }>
        <option value="default">Select a country</option>
        {
          this.props.data.data.map(country => {
            return <option key={ country.ISO2 } value={ `${ country.Slug },${ country.ISO2 }` }>{ country.Country }</option>;
          })
        }
      </select>
    );
  }
}
